// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stairways.Infra.Context;

#nullable disable

namespace Stairways.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240730181650_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stairways.Core.Models.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "811d64a1-7653-4ee8-b5fd-be5c32478317",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 417, DateTimeKind.Utc).AddTicks(9980),
                            Name = "Matemática",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 417, DateTimeKind.Utc).AddTicks(9983)
                        },
                        new
                        {
                            Id = "64a150aa-9c7f-40e0-95a4-964ef9bce46a",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(81),
                            Name = "Estatística",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(81)
                        },
                        new
                        {
                            Id = "b96e1fbe-12ff-4654-aa28-a6b7c96389b2",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(280),
                            Name = "Computação",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(280)
                        },
                        new
                        {
                            Id = "4c707630-ea14-4417-9535-3f0977bbc9e9",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(353),
                            Name = "Física",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(354)
                        },
                        new
                        {
                            Id = "845a441b-ab5d-4201-b484-1968b6baae63",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(465),
                            Name = "Química",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(465)
                        },
                        new
                        {
                            Id = "8fdec82d-713b-4426-a992-52d6b653fb90",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(549),
                            Name = "Astronomia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(550)
                        },
                        new
                        {
                            Id = "957bd779-e808-47fc-9581-3826eaedc645",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(663),
                            Name = "Geociências",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(663)
                        },
                        new
                        {
                            Id = "f02eaa3c-8db5-4294-b359-23f1a4fd4dbb",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(781),
                            Name = "Oceanografia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(781)
                        },
                        new
                        {
                            Id = "df8de6d6-1abb-425a-86ae-de9d7695c719",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(856),
                            Name = "Biologia Geral",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(857)
                        },
                        new
                        {
                            Id = "48e93af0-72f9-4247-88ab-2a57fc08da0c",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(964),
                            Name = "Bioquímica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(965)
                        },
                        new
                        {
                            Id = "a6e6a3d6-4087-420d-a3d5-c6aa85c22cb9",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1036),
                            Name = "Biofísica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1037)
                        },
                        new
                        {
                            Id = "9d84201a-fea2-4ced-8e8e-8088f576e6d9",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1131),
                            Name = "Farmacologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1131)
                        },
                        new
                        {
                            Id = "131327a8-791c-4caa-98b5-910172bf1745",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1201),
                            Name = "Fisiologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1201)
                        },
                        new
                        {
                            Id = "e9e313d6-c615-4862-b82f-a0b5b1187df0",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1341),
                            Name = "Genética",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1341)
                        },
                        new
                        {
                            Id = "72e05866-208f-4f58-b258-feed8aff4742",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1413),
                            Name = "Imunologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1413)
                        },
                        new
                        {
                            Id = "a2336a01-11bd-494c-bc7a-b89e7fc8f890",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1538),
                            Name = "Microbiologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1538)
                        },
                        new
                        {
                            Id = "0b24d54f-a93a-4d5e-a78c-d764f6061b09",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1608),
                            Name = "Parasitologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1609)
                        },
                        new
                        {
                            Id = "c730c1b0-c260-4f29-9c8a-96a7feda0a76",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1719),
                            Name = "Botânica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1720)
                        },
                        new
                        {
                            Id = "db9dd922-9b11-479c-8822-57377594ffb4",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1830),
                            Name = "Zoologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1831)
                        },
                        new
                        {
                            Id = "942ee7c6-52ab-433d-a751-2c3d86a6c432",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1903),
                            Name = "Ecologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(1904)
                        },
                        new
                        {
                            Id = "c9607f68-daa5-4da2-9297-e53d5b525df4",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2010),
                            Name = "Morfologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2011)
                        },
                        new
                        {
                            Id = "776fd232-5352-451f-affa-46c9d04503ca",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2085),
                            Name = "Engenharia Civil",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2085)
                        },
                        new
                        {
                            Id = "a9258565-fe65-45c2-b0a5-475509fb8316",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2198),
                            Name = "Engenharia Elétrica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2199)
                        },
                        new
                        {
                            Id = "97a36b63-161f-4b9d-8542-eadecc360bff",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2273),
                            Name = "Engenharia Mecânica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2274)
                        },
                        new
                        {
                            Id = "a43c1e59-b791-4739-baba-1259f92a9db7",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2380),
                            Name = "Engenharia Química",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2381)
                        },
                        new
                        {
                            Id = "02b43037-7c83-4bd3-a02f-6c0aa349f076",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2450),
                            Name = "Engenharia de Produção",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2450)
                        },
                        new
                        {
                            Id = "a7c9d890-ebe3-4ee0-845a-b70ce1e88049",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2545),
                            Name = "Engenharia de Materiais e Metalúrgica",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2545)
                        },
                        new
                        {
                            Id = "59d12bfe-a9dc-45f5-b9dd-3e434ff327e7",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2614),
                            Name = "Engenharia Sanitária",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2614)
                        },
                        new
                        {
                            Id = "49d5fe8e-554d-404c-99d9-896083eb1071",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2745),
                            Name = "Engenharia Nuclear",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2745)
                        },
                        new
                        {
                            Id = "ecebd8c2-20ff-41bf-9bdd-98f340bfd6c4",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2871),
                            Name = "Engenharia de Minas",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2872)
                        },
                        new
                        {
                            Id = "a470958a-f165-41f8-a200-63be0642595f",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2944),
                            Name = "Engenharia de Petróleo",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(2944)
                        },
                        new
                        {
                            Id = "d9bbabf1-1f4e-4c8c-9ae5-78b78dc7d75c",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3075),
                            Name = "Medicina",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3076)
                        },
                        new
                        {
                            Id = "a47a646a-3c15-4186-83d7-9c995c633ada",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3150),
                            Name = "Odontologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3151)
                        },
                        new
                        {
                            Id = "5ff2ef20-63b6-4d02-9140-fba02274b050",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3258),
                            Name = "Enfermagem",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3259)
                        },
                        new
                        {
                            Id = "69abc5c0-cb3a-40dc-a598-42c9405b5258",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3327),
                            Name = "Saúde Coletiva",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3328)
                        },
                        new
                        {
                            Id = "e09e0575-d718-4c4f-bb28-1a2556d133d1",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3436),
                            Name = "Nutrição",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3436)
                        },
                        new
                        {
                            Id = "ce472bca-76a4-49bb-a1d1-1b969abd00d5",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3507),
                            Name = "Educação Física",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3507)
                        },
                        new
                        {
                            Id = "6a280a7f-416c-40a3-8974-b88bfdfefe01",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3663),
                            Name = "Fonoaudiologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3663)
                        },
                        new
                        {
                            Id = "518d231d-ff0e-459e-bdec-2ca0260404f7",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3735),
                            Name = "Fisioterapia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3735)
                        },
                        new
                        {
                            Id = "05f0aaaf-ef62-4301-ae37-af976134c621",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3850),
                            Name = "Farmácia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3851)
                        },
                        new
                        {
                            Id = "ac0b11a9-479c-4c6f-9a74-8de6a466f4cf",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3919),
                            Name = "Agronomia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(3919)
                        },
                        new
                        {
                            Id = "f08a5b8f-b936-4eba-aebd-6e11c8fa80d0",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4030),
                            Name = "Engenharia Florestal",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4030)
                        },
                        new
                        {
                            Id = "01377241-e04c-4150-bfe6-95a83e1bbd81",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4122),
                            Name = "Engenharia Agrícola",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4122)
                        },
                        new
                        {
                            Id = "37b16a5c-2be0-4679-a730-bc980d2a0894",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4193),
                            Name = "Medicina Veterinária",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4194)
                        },
                        new
                        {
                            Id = "b8ddb18a-a40d-4783-a2bb-38819da58644",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4318),
                            Name = "Zootecnia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4318)
                        },
                        new
                        {
                            Id = "3308cadb-acdb-4f63-9956-73affaca9e05",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4391),
                            Name = "Recursos Pesqueiros e Engenharia de Pesca",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4391)
                        },
                        new
                        {
                            Id = "503bcdde-bcb6-48b4-8ce6-b0738f88a84e",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4546),
                            Name = "Ciência e Tecnologia de Alimentos",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4546)
                        },
                        new
                        {
                            Id = "476bf185-d75e-4cab-9634-366da91e2118",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4617),
                            Name = "Administração",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4618)
                        },
                        new
                        {
                            Id = "499d7803-45c3-4db6-b410-bf07da8629e3",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4731),
                            Name = "Ciências Contábeis",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4731)
                        },
                        new
                        {
                            Id = "ec1e7f90-0e12-4795-a1dd-9dc6d66e96c2",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4798),
                            Name = "Ciências Econômicas",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4799)
                        },
                        new
                        {
                            Id = "7b043772-e42c-4f8e-ae23-ae75f932cb8e",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4909),
                            Name = "Comunicação",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4910)
                        },
                        new
                        {
                            Id = "a0715523-cac3-49f7-a36b-ebe8527500e5",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4978),
                            Name = "Direito",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(4979)
                        },
                        new
                        {
                            Id = "8767339b-d401-4b2d-b27d-6ec4dc00e2ee",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5087),
                            Name = "Serviço Social",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5087)
                        },
                        new
                        {
                            Id = "d2b322b9-d156-4a73-a8dc-61731da57d97",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5199),
                            Name = "Turismo",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5199)
                        },
                        new
                        {
                            Id = "0470a27b-12ae-4695-94b6-13a4e6ffb378",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5272),
                            Name = "Arquitetura e Urbanismo",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5273)
                        },
                        new
                        {
                            Id = "a3908e72-9534-4562-a953-fe86a11733ec",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5382),
                            Name = "Planejamento Urbano e Regional",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5382)
                        },
                        new
                        {
                            Id = "58c8a18a-abdf-4fb0-8943-27f8cf8f53d2",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5453),
                            Name = "Demografia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5453)
                        },
                        new
                        {
                            Id = "a342b53e-c1c0-49f5-9143-3ab46849bb74",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5544),
                            Name = "Museologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5545)
                        },
                        new
                        {
                            Id = "5272dd5f-732f-4821-81c8-801b5bcba081",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5613),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5613)
                        },
                        new
                        {
                            Id = "d439e9a3-b2d5-4b4b-a52f-3a36a0b61720",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5738),
                            Name = "Sociologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5738)
                        },
                        new
                        {
                            Id = "40597f88-887c-4bd4-9bee-d39f293add4a",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5807),
                            Name = "Antropologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5808)
                        },
                        new
                        {
                            Id = "3bcdfc9b-e365-4af1-82e7-dffa47a6f0f4",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5967),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(5968)
                        },
                        new
                        {
                            Id = "34e432a1-55c6-4e09-9eb5-b4cbb2c5cc9f",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6036),
                            Name = "Geografia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6036)
                        },
                        new
                        {
                            Id = "8c2e1094-4a8d-44fd-84b3-b922dd19d3fe",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6140),
                            Name = "Psicologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6141)
                        },
                        new
                        {
                            Id = "428a03e4-5f61-4c01-82bb-c1c81cbd04a0",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6248),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6248)
                        },
                        new
                        {
                            Id = "a777c4c0-6a7b-4539-bdfc-89b6037207b8",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6319),
                            Name = "Teologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6319)
                        },
                        new
                        {
                            Id = "965f6972-4aa5-4189-bfc7-6b93da6c0fd3",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6430),
                            Name = "Ciência Política",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6430)
                        },
                        new
                        {
                            Id = "8e9d2607-2b29-4db3-9ee2-3e66dd8d9492",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6501),
                            Name = "Relações Internacionais",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6502)
                        },
                        new
                        {
                            Id = "cb4ad5ca-ab8a-4903-ae3b-3277c0d280f6",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6611),
                            Name = "Linguística",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6611)
                        },
                        new
                        {
                            Id = "6599a041-6d89-4a53-87d9-b6be3bba235f",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Letras",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6686)
                        },
                        new
                        {
                            Id = "cec599d6-a5cf-4225-90a0-9958f5a76410",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6794),
                            Name = "Artes",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6794)
                        },
                        new
                        {
                            Id = "5558befa-5f4c-4aa1-85e6-12027aff088e",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6864),
                            Name = "Música",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6865)
                        },
                        new
                        {
                            Id = "52320464-45df-4581-8831-d61d18d612c1",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6955),
                            Name = "Teatro",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(6956)
                        },
                        new
                        {
                            Id = "46b5cd15-5b19-4e52-bfa5-e4cfed245cc1",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7026),
                            Name = "Artes Visuais",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7026)
                        },
                        new
                        {
                            Id = "54f0268a-50e2-4ec2-8721-d5e1025508bd",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7150),
                            Name = "Ciência e Tecnologia Ambiental",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7151)
                        },
                        new
                        {
                            Id = "5aa6bf5f-fa30-4b2c-b033-ce93f28e9abb",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7326),
                            Name = "Ciência e Tecnologia dos Materiais",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7328)
                        },
                        new
                        {
                            Id = "26bb7096-e13c-4f08-a835-9c70bbfaa603",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7468),
                            Name = "Interdisciplinar",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7468)
                        },
                        new
                        {
                            Id = "9fdae4a1-eaee-4947-9fd8-6b0b0aee06ff",
                            CreatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7598),
                            Name = "Biotecnologia",
                            UpdatedAt = new DateTime(2024, 7, 30, 18, 16, 49, 418, DateTimeKind.Utc).AddTicks(7598)
                        });
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Meta", "Stairways.Core.Models.RoadmapEntity.Meta#RoadmapMeta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ImageURL")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("Privacy")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Roadmaps", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.HasOne("Stairways.Core.Models.UserEntity", "Author")
                        .WithMany("Roadmaps")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stairways.Core.Models.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
