// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stairways.Infra.Context;

#nullable disable

namespace Stairways.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726133953_SeedCatecory")]
    partial class SeedCatecory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stairways.Core.Models.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fa1dc71f-bff0-476b-b7c2-2d62ea274c6d",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(496),
                            Name = "Matemática",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(498)
                        },
                        new
                        {
                            Id = "4479de5a-bb10-48b7-bbda-c58a3620919e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(638),
                            Name = "Estatística",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(638)
                        },
                        new
                        {
                            Id = "7eba93e1-29d0-48d7-bf7e-2c4c3e7ad21a",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(721),
                            Name = "Computação",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(722)
                        },
                        new
                        {
                            Id = "631388bc-6a76-408c-be70-913e7368aaa3",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(829),
                            Name = "Física",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(829)
                        },
                        new
                        {
                            Id = "9f98d95e-d65a-477a-b138-c8e6fa04c836",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(901),
                            Name = "Química",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(901)
                        },
                        new
                        {
                            Id = "0c8aa167-f9f3-44f3-a8a2-b5058023ca93",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1004),
                            Name = "Astronomia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1005)
                        },
                        new
                        {
                            Id = "277d1cfc-c913-4bc6-895f-2d09fa6aa118",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1075),
                            Name = "Geociências",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1076)
                        },
                        new
                        {
                            Id = "99ddbd2d-d2db-4fe0-80be-191c821c5f00",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1205),
                            Name = "Oceanografia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1205)
                        },
                        new
                        {
                            Id = "d61704ea-db19-416b-94b4-8d4b84b0c8c3",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1276),
                            Name = "Biologia Geral",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1276)
                        },
                        new
                        {
                            Id = "19b7fb1f-16a1-469f-93d7-b9e74233d44e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1411),
                            Name = "Bioquímica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1411)
                        },
                        new
                        {
                            Id = "9a693f21-0659-4b4b-aeaa-a4d612f75077",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1530),
                            Name = "Biofísica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1531)
                        },
                        new
                        {
                            Id = "d7d42c18-1ac6-4b40-a0fa-94d27ec83288",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1603),
                            Name = "Farmacologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1603)
                        },
                        new
                        {
                            Id = "9b74c11f-4658-4670-a7ad-2d2a8832d9a1",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1836),
                            Name = "Fisiologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1837)
                        },
                        new
                        {
                            Id = "a3d9c3b5-732e-4ff1-b260-216111e1ed4f",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1903),
                            Name = "Genética",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1903)
                        },
                        new
                        {
                            Id = "9438f6ad-9f7f-4fca-87f7-caa7990c925e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1997),
                            Name = "Imunologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(1998)
                        },
                        new
                        {
                            Id = "460d2a1a-6516-467b-a11f-67663030d51b",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2065),
                            Name = "Microbiologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2065)
                        },
                        new
                        {
                            Id = "a73c179c-f5e3-4e2e-9709-445802d8384b",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2179),
                            Name = "Parasitologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2179)
                        },
                        new
                        {
                            Id = "c551589f-0a15-4711-8d0a-5fb6ae63bf53",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2244),
                            Name = "Botânica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2244)
                        },
                        new
                        {
                            Id = "e5a85dc6-b385-4d1e-ace8-35ca4e600788",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2338),
                            Name = "Zoologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2338)
                        },
                        new
                        {
                            Id = "999cacc8-76c8-4d67-9c00-df3f4f0545f9",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2402),
                            Name = "Ecologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2402)
                        },
                        new
                        {
                            Id = "507cc554-894d-4dec-b0da-fe80a89ce5b7",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2590),
                            Name = "Morfologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2590)
                        },
                        new
                        {
                            Id = "450ce619-88de-4087-ad3b-16c90cad86aa",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2658),
                            Name = "Engenharia Civil",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2658)
                        },
                        new
                        {
                            Id = "ff743115-7c2d-4b23-900b-7af062379a42",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2743),
                            Name = "Engenharia Elétrica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2743)
                        },
                        new
                        {
                            Id = "37e3f0ef-c61d-47da-bd70-5569a119fdde",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2886),
                            Name = "Engenharia Mecânica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2886)
                        },
                        new
                        {
                            Id = "6b7df305-50d9-4e19-b60d-8d9e3bd204d8",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2952),
                            Name = "Engenharia Química",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(2952)
                        },
                        new
                        {
                            Id = "ceb4199a-6a22-4acb-a61a-68183c253a05",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3059),
                            Name = "Engenharia de Produção",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3059)
                        },
                        new
                        {
                            Id = "30c5af51-ec55-4457-933f-8e8f712eef84",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3123),
                            Name = "Engenharia de Materiais e Metalúrgica",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3124)
                        },
                        new
                        {
                            Id = "2a441f16-d1fb-450d-9be1-fab7509c7081",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3219),
                            Name = "Engenharia Sanitária",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3220)
                        },
                        new
                        {
                            Id = "1b02a49b-aea9-47e2-b032-d2f585a3a0ce",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3285),
                            Name = "Engenharia Nuclear",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3286)
                        },
                        new
                        {
                            Id = "ad3c5d61-db6c-4b45-9d15-2276660411eb",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3379),
                            Name = "Engenharia de Minas",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3379)
                        },
                        new
                        {
                            Id = "e21ab050-4043-4da1-86a9-48618e744976",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3442),
                            Name = "Engenharia de Petróleo",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3443)
                        },
                        new
                        {
                            Id = "fbef1515-bceb-4b43-a6e6-ccdc9c7f8884",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3539),
                            Name = "Medicina",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3539)
                        },
                        new
                        {
                            Id = "0c5e1042-9379-4a2d-a6e4-5754f2cc01f7",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3602),
                            Name = "Odontologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3602)
                        },
                        new
                        {
                            Id = "21a87a8a-a227-4120-8121-2db76ffa3e48",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3700),
                            Name = "Enfermagem",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3701)
                        },
                        new
                        {
                            Id = "9dce7f8d-6f13-460c-aba6-0a8e99c149be",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3795),
                            Name = "Saúde Coletiva",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3795)
                        },
                        new
                        {
                            Id = "fd35d6f2-1b61-4685-9480-44f609f5b8f9",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3859),
                            Name = "Nutrição",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3860)
                        },
                        new
                        {
                            Id = "699f58fd-e1fb-41ac-9711-e02088095dd2",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3941),
                            Name = "Educação Física",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(3942)
                        },
                        new
                        {
                            Id = "7e817157-26c6-4fd3-99ca-6454aeeb1f83",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4005),
                            Name = "Fonoaudiologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4006)
                        },
                        new
                        {
                            Id = "82061c88-0bc1-4007-a60d-6a9961a2ad6e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4111),
                            Name = "Fisioterapia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4111)
                        },
                        new
                        {
                            Id = "9526b72c-b73d-421b-9efb-24ca1cd581e0",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4179),
                            Name = "Farmácia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4179)
                        },
                        new
                        {
                            Id = "d79f3777-28bb-4c86-896b-53e36e593a64",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4297),
                            Name = "Agronomia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4297)
                        },
                        new
                        {
                            Id = "c61e7138-1416-4a26-b5b3-81923bcfc0fb",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4361),
                            Name = "Engenharia Florestal",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4361)
                        },
                        new
                        {
                            Id = "f4c3e027-932b-4d09-905e-9f8dd328b9d1",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4454),
                            Name = "Engenharia Agrícola",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4454)
                        },
                        new
                        {
                            Id = "d47cdaad-f85a-4261-bfaa-a17e90447d06",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4518),
                            Name = "Medicina Veterinária",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4518)
                        },
                        new
                        {
                            Id = "fce432c4-bbcc-4861-8b8a-b4211796082d",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4612),
                            Name = "Zootecnia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4613)
                        },
                        new
                        {
                            Id = "a676a7db-8f74-4e0d-b52a-7a6703e903df",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4712),
                            Name = "Recursos Pesqueiros e Engenharia de Pesca",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4712)
                        },
                        new
                        {
                            Id = "966d296e-0a1c-41ec-863d-7e3f0de48c9c",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4778),
                            Name = "Ciência e Tecnologia de Alimentos",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4778)
                        },
                        new
                        {
                            Id = "df0206bc-ccdb-4694-ab56-9114e2c6f22e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4861),
                            Name = "Administração",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4862)
                        },
                        new
                        {
                            Id = "cfa6dd2c-3a11-4da8-9d30-fb2e13989557",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4926),
                            Name = "Ciências Contábeis",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(4926)
                        },
                        new
                        {
                            Id = "f4bb6e52-6052-4587-aa44-a2d16d86b038",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5035),
                            Name = "Ciências Econômicas",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5036)
                        },
                        new
                        {
                            Id = "4771ea8c-e46b-41ad-a7fb-42ec82abac5f",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5100),
                            Name = "Comunicação",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5100)
                        },
                        new
                        {
                            Id = "d6ade87b-b4f6-484a-b8c9-6785c9a6c30e",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5226),
                            Name = "Direito",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5227)
                        },
                        new
                        {
                            Id = "f6c430cf-65e0-492a-8739-5998dd8056a8",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5289),
                            Name = "Serviço Social",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5289)
                        },
                        new
                        {
                            Id = "ea97ef4f-da47-4ef2-8a7f-e44c91db9fbf",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5391),
                            Name = "Turismo",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5392)
                        },
                        new
                        {
                            Id = "ce0e8bbd-e145-4f3e-9178-23edb0da0d97",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5455),
                            Name = "Arquitetura e Urbanismo",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5455)
                        },
                        new
                        {
                            Id = "84545f76-3ecb-4d81-9b7a-0ee1356e4938",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5574),
                            Name = "Planejamento Urbano e Regional",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5574)
                        },
                        new
                        {
                            Id = "d43c2239-1c0b-4304-b40a-4cff6581c79d",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5668),
                            Name = "Demografia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5668)
                        },
                        new
                        {
                            Id = "100166b1-5bf4-4218-98a5-6bba7aea1331",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5733),
                            Name = "Museologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5733)
                        },
                        new
                        {
                            Id = "2f5f1861-691f-4c36-91a8-fc7bb394008c",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5827),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5828)
                        },
                        new
                        {
                            Id = "e8da4567-3a52-430b-a4c2-d62bfcef0a31",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5891),
                            Name = "Sociologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5892)
                        },
                        new
                        {
                            Id = "4e8adcb0-70bc-4ce3-8de2-daad868336f3",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5984),
                            Name = "Antropologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(5985)
                        },
                        new
                        {
                            Id = "5527ce9d-30cb-4fba-ad3a-37a5f2786a96",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6049),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6049)
                        },
                        new
                        {
                            Id = "cfe5c332-e060-46db-af7b-9053724f72ef",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6196),
                            Name = "Geografia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6196)
                        },
                        new
                        {
                            Id = "bb1e5d5a-79b8-4fae-b497-7e72351d2c8f",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6266),
                            Name = "Psicologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6266)
                        },
                        new
                        {
                            Id = "ea71c6d7-6a08-4679-8c07-c672af04927a",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6414),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6415)
                        },
                        new
                        {
                            Id = "19da0f5c-bd8e-4c90-a7cb-eceeddc28fcb",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6482),
                            Name = "Teologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6482)
                        },
                        new
                        {
                            Id = "5621d3a8-b0fd-4533-9071-e297c9519a75",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6589),
                            Name = "Ciência Política",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6589)
                        },
                        new
                        {
                            Id = "92c0916e-a680-42b3-8932-a8e04b35c601",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6680),
                            Name = "Relações Internacionais",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6680)
                        },
                        new
                        {
                            Id = "5d3a7140-58c1-409c-8273-9a0e77e08b65",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6744),
                            Name = "Linguística",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6744)
                        },
                        new
                        {
                            Id = "df5adb8a-76ac-4143-a7e5-97b329e04001",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6839),
                            Name = "Letras",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6839)
                        },
                        new
                        {
                            Id = "a7c6344e-8443-4859-b990-58a536cc1348",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6903),
                            Name = "Artes",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(6903)
                        },
                        new
                        {
                            Id = "ed68d4e1-dba7-4c32-a652-41e0d4e9b6f2",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7000),
                            Name = "Música",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7001)
                        },
                        new
                        {
                            Id = "01f6ba62-ff48-488b-be73-9539c2281473",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7065),
                            Name = "Teatro",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7066)
                        },
                        new
                        {
                            Id = "4855d74d-a10b-4437-9686-e561e0545c69",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7158),
                            Name = "Artes Visuais",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7158)
                        },
                        new
                        {
                            Id = "d8f424d2-c525-4c38-be2b-9ff0d1ec9fd5",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7221),
                            Name = "Ciência e Tecnologia Ambiental",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7221)
                        },
                        new
                        {
                            Id = "203d8e68-2eec-4ed7-81dd-c9ade22434c7",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7314),
                            Name = "Ciência e Tecnologia dos Materiais",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7315)
                        },
                        new
                        {
                            Id = "e869be2a-d288-41c2-acdb-2de75291d843",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7378),
                            Name = "Interdisciplinar",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7378)
                        },
                        new
                        {
                            Id = "18337799-f7e1-45ee-820b-c6f2f1b51112",
                            CreatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7458),
                            Name = "Biotecnologia",
                            UpdatedAt = new DateTime(2024, 7, 26, 13, 39, 53, 18, DateTimeKind.Utc).AddTicks(7459)
                        });
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Meta", "Stairways.Core.Models.RoadmapEntity.Meta#RoadmapMeta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ImageURL")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("Privacity")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("Roadmaps", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.HasOne("Stairways.Core.Models.UserEntity", "Author")
                        .WithMany("Roadmaps")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stairways.Core.Models.CategoryEntity", "Category")
                        .WithOne()
                        .HasForeignKey("Stairways.Core.Models.RoadmapEntity", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
