// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stairways.Infra.Context;

#nullable disable

namespace Stairways.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240813124052_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stairways.Core.Models.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e453e2bb-e065-4c8a-81fe-2534568d4770",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1250),
                            Name = "Matemática",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1276)
                        },
                        new
                        {
                            Id = "5691cab9-0c76-4aca-ab74-d194312d89e2",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1402),
                            Name = "Estatística",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1403)
                        },
                        new
                        {
                            Id = "b436ce48-7cf3-4b58-b250-1699b67e2634",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1489),
                            Name = "Computação",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1490)
                        },
                        new
                        {
                            Id = "3ca0bc64-45a3-453e-b6ff-288c36355fad",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1567),
                            Name = "Física",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1567)
                        },
                        new
                        {
                            Id = "6b32fd09-8d40-49c6-8ecd-3db3557d36bd",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1636),
                            Name = "Química",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1637)
                        },
                        new
                        {
                            Id = "11c4c4af-a00f-42a9-bc49-45e4f60fd89e",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1711),
                            Name = "Astronomia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1712)
                        },
                        new
                        {
                            Id = "40f109c2-6fd5-492c-be37-bad1fdd604fb",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1786),
                            Name = "Geociências",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1786)
                        },
                        new
                        {
                            Id = "af65737d-325d-4c93-b1ef-a7d7dbc1d436",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1855),
                            Name = "Oceanografia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1855)
                        },
                        new
                        {
                            Id = "7c14db81-3ba9-4de2-8403-cfb7d34ec74e",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1928),
                            Name = "Biologia Geral",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1928)
                        },
                        new
                        {
                            Id = "314948c6-b84f-4d3f-a578-6e5738fa15ec",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1996),
                            Name = "Bioquímica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(1996)
                        },
                        new
                        {
                            Id = "f40cb36d-eb31-404c-adc5-d50a93976a8d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2073),
                            Name = "Biofísica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2073)
                        },
                        new
                        {
                            Id = "63c92b6c-9b1a-4581-881a-be97b21ee4cd",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2141),
                            Name = "Farmacologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2141)
                        },
                        new
                        {
                            Id = "e4c17478-3138-4123-b953-28dbb78ab364",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2214),
                            Name = "Fisiologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2214)
                        },
                        new
                        {
                            Id = "844191cd-8d74-496f-86f6-88a36c8843d8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2282),
                            Name = "Genética",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2282)
                        },
                        new
                        {
                            Id = "538d9bea-7744-4d0f-ba97-ce3ebb458128",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2356),
                            Name = "Imunologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2356)
                        },
                        new
                        {
                            Id = "25c403fa-1c6c-4954-8e15-4b3f919d0213",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2423),
                            Name = "Microbiologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2424)
                        },
                        new
                        {
                            Id = "88cc67e7-fbb3-4115-a76b-769c860dded2",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2597),
                            Name = "Parasitologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2597)
                        },
                        new
                        {
                            Id = "142e75cd-0428-4edb-8b13-40f16410f62b",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2684),
                            Name = "Botânica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2685)
                        },
                        new
                        {
                            Id = "bbef4774-c52b-4798-a3d2-70d4577d785d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2758),
                            Name = "Zoologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2759)
                        },
                        new
                        {
                            Id = "978d2192-090a-4113-bc3d-6dd3d99b5534",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2831),
                            Name = "Ecologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2831)
                        },
                        new
                        {
                            Id = "ccf82e9f-e7a6-4244-99f0-a98cd4a6545d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2898),
                            Name = "Morfologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2899)
                        },
                        new
                        {
                            Id = "4d23f36c-3a7f-4da4-9ee5-bcc13dac78d6",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2972),
                            Name = "Engenharia Civil",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(2973)
                        },
                        new
                        {
                            Id = "a6a87b64-42ad-4148-b59e-93e2f656928f",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3041),
                            Name = "Engenharia Elétrica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3042)
                        },
                        new
                        {
                            Id = "5cd2de6e-5d3a-4fcc-9c96-c1ab069ddeb1",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3213),
                            Name = "Engenharia Mecânica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3213)
                        },
                        new
                        {
                            Id = "a99de8c3-269b-4c9f-a59f-c6984001fb3b",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3285),
                            Name = "Engenharia Química",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3286)
                        },
                        new
                        {
                            Id = "d96271e9-10db-41b2-810f-cddea5f98a03",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3397),
                            Name = "Engenharia de Produção",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3397)
                        },
                        new
                        {
                            Id = "4609cfa4-41d2-4729-8348-880ef44c26de",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3469),
                            Name = "Engenharia de Materiais e Metalúrgica",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3469)
                        },
                        new
                        {
                            Id = "b33ce800-eda4-4815-b1b0-6eca6c207e41",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3580),
                            Name = "Engenharia Sanitária",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3580)
                        },
                        new
                        {
                            Id = "ee5a53c4-5878-4477-9b42-a31885e7b138",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3652),
                            Name = "Engenharia Nuclear",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3652)
                        },
                        new
                        {
                            Id = "4b36d558-1a5e-4bea-91da-877357da5088",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3762),
                            Name = "Engenharia de Minas",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3762)
                        },
                        new
                        {
                            Id = "c9f38fc9-b41d-4c81-ac43-0cf274ffd771",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3868),
                            Name = "Engenharia de Petróleo",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3868)
                        },
                        new
                        {
                            Id = "355845f9-9da5-4a24-86c0-7658e383dee2",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3939),
                            Name = "Medicina",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(3939)
                        },
                        new
                        {
                            Id = "89c01d21-caa4-4db0-93f8-106741942731",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4054),
                            Name = "Odontologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4055)
                        },
                        new
                        {
                            Id = "1290425d-9758-4abf-b6f1-a5da81110214",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4126),
                            Name = "Enfermagem",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4126)
                        },
                        new
                        {
                            Id = "56afb885-3d8a-4d1b-b8fa-3a424fbbf064",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4297),
                            Name = "Saúde Coletiva",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4297)
                        },
                        new
                        {
                            Id = "dd594e0e-2a2a-4956-935d-3dc63b61d483",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4368),
                            Name = "Nutrição",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4369)
                        },
                        new
                        {
                            Id = "e39ae74e-3748-418c-8a67-875fc7ad6650",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4496),
                            Name = "Educação Física",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4497)
                        },
                        new
                        {
                            Id = "ca2aec5d-481c-40c0-b4f5-054cb70738aa",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4564),
                            Name = "Fonoaudiologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4565)
                        },
                        new
                        {
                            Id = "ea8ffe8c-e46a-4f8e-bdf0-b203298a9465",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4677),
                            Name = "Fisioterapia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4677)
                        },
                        new
                        {
                            Id = "9045cba9-8e28-4115-9144-b81b78f2fe0d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4745),
                            Name = "Farmácia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4745)
                        },
                        new
                        {
                            Id = "b51b12ff-b7c3-41be-8afc-eefed0f95703",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4855),
                            Name = "Agronomia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4856)
                        },
                        new
                        {
                            Id = "e4ca2452-93f4-453a-bac0-9f1ed94a62fc",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4962),
                            Name = "Engenharia Florestal",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(4962)
                        },
                        new
                        {
                            Id = "17fb4cc1-90af-4440-a76f-06f9d18c51c8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5034),
                            Name = "Engenharia Agrícola",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5034)
                        },
                        new
                        {
                            Id = "300c6359-3709-4c71-8d54-90adac1f864d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5141),
                            Name = "Medicina Veterinária",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5141)
                        },
                        new
                        {
                            Id = "ad727508-1c98-4961-888c-11c186422e1a",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5210),
                            Name = "Zootecnia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = "f9b7f3d4-cb01-4a1b-beed-26f0046c2cd8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5319),
                            Name = "Recursos Pesqueiros e Engenharia de Pesca",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5319)
                        },
                        new
                        {
                            Id = "41123564-fa43-4efa-bc5b-993624f5c99a",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5387),
                            Name = "Ciência e Tecnologia de Alimentos",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5388)
                        },
                        new
                        {
                            Id = "cae0782e-3211-478c-b6f1-d797835f586c",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5480),
                            Name = "Administração",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5480)
                        },
                        new
                        {
                            Id = "e0cc3efa-47f0-4532-94f2-2ea4fb513a2e",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5547),
                            Name = "Ciências Contábeis",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5547)
                        },
                        new
                        {
                            Id = "cb9d26af-04ee-48fb-af11-d416d31d337d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5676),
                            Name = "Ciências Econômicas",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5677)
                        },
                        new
                        {
                            Id = "dcbdfe05-a7be-4c90-92a7-e11a60e901e8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5749),
                            Name = "Comunicação",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5750)
                        },
                        new
                        {
                            Id = "400867d1-b827-4879-8dd6-7444ef591034",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5875),
                            Name = "Direito",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5875)
                        },
                        new
                        {
                            Id = "429ca40b-ecc7-429a-b7a5-16b1f96dd638",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5971),
                            Name = "Serviço Social",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(5972)
                        },
                        new
                        {
                            Id = "252f793a-0a98-498c-9441-801b5ff672db",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6043),
                            Name = "Turismo",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6044)
                        },
                        new
                        {
                            Id = "26761e26-07c0-442c-ac38-cff1424b26cf",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6117),
                            Name = "Arquitetura e Urbanismo",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6118)
                        },
                        new
                        {
                            Id = "7720c88a-a02f-4826-a5e2-7b710fb449ab",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6186),
                            Name = "Planejamento Urbano e Regional",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6186)
                        },
                        new
                        {
                            Id = "6ca8c11e-3017-40d9-bf70-671b7b28d0ac",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6259),
                            Name = "Demografia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6259)
                        },
                        new
                        {
                            Id = "d5530d22-33d6-4bc5-8065-6bc47c9d1d29",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6328),
                            Name = "Museologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6328)
                        },
                        new
                        {
                            Id = "64ebd390-8e92-4ea8-97c4-b6cc9ec2f58a",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6489),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6489)
                        },
                        new
                        {
                            Id = "f13e0030-8375-4642-9cec-56bcee59049f",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6570),
                            Name = "Sociologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = "ce75f6e0-e9a8-44b5-baa7-3ebcac8771e8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6647),
                            Name = "Antropologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6647)
                        },
                        new
                        {
                            Id = "593d9cb9-1076-440c-afd4-2f76e9fcc316",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6715),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6715)
                        },
                        new
                        {
                            Id = "c056abc1-6218-4db8-a5a4-c470916a98c7",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6787),
                            Name = "Geografia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6788)
                        },
                        new
                        {
                            Id = "69d62521-8ad7-4fc5-a11f-46bf6e57f670",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6857),
                            Name = "Psicologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6857)
                        },
                        new
                        {
                            Id = "fd11794a-8379-4014-b5cc-f24e8159a253",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6931),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(6932)
                        },
                        new
                        {
                            Id = "fc0d73dd-82a3-41bb-810d-2d8a4b5e42c1",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7026),
                            Name = "Teologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7027)
                        },
                        new
                        {
                            Id = "920ca741-0f88-4fba-9ba9-4e4be6751488",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7096),
                            Name = "Ciência Política",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7096)
                        },
                        new
                        {
                            Id = "f1464fb3-68f6-4400-ab6e-a6121e35eb62",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7174),
                            Name = "Relações Internacionais",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7174)
                        },
                        new
                        {
                            Id = "82f84613-4d95-4a3d-8786-6f701be101a9",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7241),
                            Name = "Linguística",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7241)
                        },
                        new
                        {
                            Id = "15b21e9c-e554-426b-949d-76b0554b0a8d",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7314),
                            Name = "Letras",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7314)
                        },
                        new
                        {
                            Id = "46c57a85-710c-43a8-b3cf-f69df6d0c50c",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7380),
                            Name = "Artes",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7381)
                        },
                        new
                        {
                            Id = "3b84e5ac-27e0-47d6-82ca-e4e0991ad989",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7453),
                            Name = "Música",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7453)
                        },
                        new
                        {
                            Id = "50ecfec2-cc9e-4e93-be9f-92db0c024ced",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7521),
                            Name = "Teatro",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7521)
                        },
                        new
                        {
                            Id = "7370fd18-b662-47d5-9d9e-9c0f5fdf839b",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7595),
                            Name = "Artes Visuais",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7596)
                        },
                        new
                        {
                            Id = "38a6e765-8c78-4c5e-bf06-149b35cd8c02",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7666),
                            Name = "Ciência e Tecnologia Ambiental",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7666)
                        },
                        new
                        {
                            Id = "429749a9-d489-4d32-ac7a-292fc226eefe",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7740),
                            Name = "Ciência e Tecnologia dos Materiais",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7740)
                        },
                        new
                        {
                            Id = "1381ecb1-2559-4025-ab46-d135ee3b55b3",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7813),
                            Name = "Interdisciplinar",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7814)
                        },
                        new
                        {
                            Id = "cd595661-3547-4010-9749-5fcb2d8a98f6",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7882),
                            Name = "Biotecnologia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7883)
                        },
                        new
                        {
                            Id = "932d45b1-01cb-4cb7-a3ae-2edc918e27e8",
                            CreatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7956),
                            Name = "Gastronomia",
                            UpdatedAt = new DateTime(2024, 8, 13, 12, 40, 51, 430, DateTimeKind.Utc).AddTicks(7956)
                        });
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Meta", "Stairways.Core.Models.RoadmapEntity.Meta#RoadmapMeta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ImageURL")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("Privacy")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Roadmaps", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("DoneItemsHashs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.HasOne("Stairways.Core.Models.UserEntity", "Author")
                        .WithMany("Roadmaps")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stairways.Core.Models.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
