// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stairways.Infra.Context;

#nullable disable

namespace Stairways.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240810125738_AddedDoneItemsInUser")]
    partial class AddedDoneItemsInUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stairways.Core.Models.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dc10b831-86c3-4c03-84ff-301c68aa354c",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(1938),
                            Name = "Matemática",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(1940)
                        },
                        new
                        {
                            Id = "f47e06df-f600-4a5b-8847-810d6f45359c",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2037),
                            Name = "Estatística",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2037)
                        },
                        new
                        {
                            Id = "80d4a57c-1de7-4fd2-b47f-d13eb5834f11",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2172),
                            Name = "Computação",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2173)
                        },
                        new
                        {
                            Id = "2b8f996c-334f-4ee0-b768-a3e8a4e2d245",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2254),
                            Name = "Física",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2255)
                        },
                        new
                        {
                            Id = "b1a40e69-e881-42ec-9887-44bc628ef081",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2374),
                            Name = "Química",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2374)
                        },
                        new
                        {
                            Id = "a22d99bb-3cb1-4b78-bc67-47056aa97423",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2442),
                            Name = "Astronomia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2442)
                        },
                        new
                        {
                            Id = "5f3af4eb-075a-4320-a374-393d203fd8cf",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2546),
                            Name = "Geociências",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2546)
                        },
                        new
                        {
                            Id = "1fa7ec4e-f87b-488a-83bf-4fd4d9bf87bc",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2612),
                            Name = "Oceanografia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2613)
                        },
                        new
                        {
                            Id = "abeedef6-ebf7-4edc-87fe-1b530f623aaf",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2716),
                            Name = "Biologia Geral",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2717)
                        },
                        new
                        {
                            Id = "6b7a4f8e-ad15-4232-84aa-fc27de67de38",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2782),
                            Name = "Bioquímica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2782)
                        },
                        new
                        {
                            Id = "92a8fe51-3dbb-4176-9cb5-cdc8df40b055",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2884),
                            Name = "Biofísica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2884)
                        },
                        new
                        {
                            Id = "78127251-d25b-410b-be70-24b8ebd87508",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2984),
                            Name = "Farmacologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(2985)
                        },
                        new
                        {
                            Id = "c30e20b6-9d13-4265-bd5f-15f1675e3d62",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3051),
                            Name = "Fisiologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3052)
                        },
                        new
                        {
                            Id = "92e5aa94-9770-4a78-9523-5dc1485545ae",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3162),
                            Name = "Genética",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3162)
                        },
                        new
                        {
                            Id = "e7e23f27-ca2b-47df-b3b5-aac6a217be7f",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3230),
                            Name = "Imunologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3230)
                        },
                        new
                        {
                            Id = "e58419cb-5fb1-4dea-9ef6-bcdcc98cc201",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3319),
                            Name = "Microbiologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3319)
                        },
                        new
                        {
                            Id = "8cdb3f98-11f7-4d2a-b02a-efcfc482cfe6",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3385),
                            Name = "Parasitologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3385)
                        },
                        new
                        {
                            Id = "2a418cad-5bf8-4b6d-a3e2-936b84b92c01",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3501),
                            Name = "Botânica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3501)
                        },
                        new
                        {
                            Id = "43d1056d-7501-4c9f-b03c-c4851299d53a",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3567),
                            Name = "Zoologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3567)
                        },
                        new
                        {
                            Id = "802ff030-0ad0-4d0b-83e1-0ed7c590872f",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3686),
                            Name = "Ecologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3686)
                        },
                        new
                        {
                            Id = "908f92fc-f582-44a3-beb4-381d04213653",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3933),
                            Name = "Morfologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(3934)
                        },
                        new
                        {
                            Id = "9fa80b40-1754-4117-9cc8-cd6f03df7dfd",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4042),
                            Name = "Engenharia Civil",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4042)
                        },
                        new
                        {
                            Id = "4c897a7e-ce57-4ba7-96c8-d1ca7489eb6e",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4237),
                            Name = "Engenharia Elétrica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4237)
                        },
                        new
                        {
                            Id = "94efab42-e6d2-4baa-9f52-31ee7cc5a8c9",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4323),
                            Name = "Engenharia Mecânica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4324)
                        },
                        new
                        {
                            Id = "ce2e459f-aca5-4abf-9fb3-5500303a871f",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4434),
                            Name = "Engenharia Química",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4434)
                        },
                        new
                        {
                            Id = "e80b016d-2d40-49f6-b418-379d223b9c19",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4507),
                            Name = "Engenharia de Produção",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4507)
                        },
                        new
                        {
                            Id = "d9b2e892-d5fd-4458-bc71-28394aae2175",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4739),
                            Name = "Engenharia de Materiais e Metalúrgica",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4739)
                        },
                        new
                        {
                            Id = "765e0243-215f-423e-91e0-e0a8964f6ff3",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4807),
                            Name = "Engenharia Sanitária",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4808)
                        },
                        new
                        {
                            Id = "11f12f12-94f2-48fd-9df7-adb041f2931b",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4906),
                            Name = "Engenharia Nuclear",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4907)
                        },
                        new
                        {
                            Id = "1d605742-8d25-4ca0-8f8c-d8633a466cee",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4971),
                            Name = "Engenharia de Minas",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(4972)
                        },
                        new
                        {
                            Id = "342cca1b-7cd1-4e2d-8047-e0daf8095a52",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5057),
                            Name = "Engenharia de Petróleo",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5058)
                        },
                        new
                        {
                            Id = "33224134-ec17-4356-bcb6-d74d8ea05ecd",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5122),
                            Name = "Medicina",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5122)
                        },
                        new
                        {
                            Id = "da2a0956-42b8-4527-97f4-1ba66182d90d",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5239),
                            Name = "Odontologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5240)
                        },
                        new
                        {
                            Id = "b4f0f088-2e81-460c-abf1-ac81953ab476",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5359),
                            Name = "Enfermagem",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5359)
                        },
                        new
                        {
                            Id = "cb09e518-03d8-4fc4-a1e8-15b644a5e51a",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5426),
                            Name = "Saúde Coletiva",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5426)
                        },
                        new
                        {
                            Id = "36e5d690-e42d-4546-ab65-538914b5391c",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5526),
                            Name = "Nutrição",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5527)
                        },
                        new
                        {
                            Id = "95a11e77-5a08-459d-a369-cb6a5493a886",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5596),
                            Name = "Educação Física",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5596)
                        },
                        new
                        {
                            Id = "48df2c8f-cee4-4e96-9c0e-9f68c16f3879",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5698),
                            Name = "Fonoaudiologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5699)
                        },
                        new
                        {
                            Id = "11ae8594-0551-4b9d-9e1c-0ee6f6942c8a",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5764),
                            Name = "Fisioterapia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5764)
                        },
                        new
                        {
                            Id = "4716f8b2-24ca-4735-a413-0483fb357aa4",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5868),
                            Name = "Farmácia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5868)
                        },
                        new
                        {
                            Id = "97c3c805-9c5d-426f-b361-d7bcad898948",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5933),
                            Name = "Agronomia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(5934)
                        },
                        new
                        {
                            Id = "b9acc46d-2337-4c9f-af08-623ef0ff8834",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6057),
                            Name = "Engenharia Florestal",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6057)
                        },
                        new
                        {
                            Id = "09454aba-2027-4389-889d-c9f331123625",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6123),
                            Name = "Engenharia Agrícola",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6123)
                        },
                        new
                        {
                            Id = "e781b6bf-e3b9-403b-a8ed-9f42e086338f",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6229),
                            Name = "Medicina Veterinária",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6229)
                        },
                        new
                        {
                            Id = "d26546c7-fcb4-4be0-a122-1f310a1322fe",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6294),
                            Name = "Zootecnia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6294)
                        },
                        new
                        {
                            Id = "663fa4ba-c068-48b7-b9c2-db83179329c1",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6387),
                            Name = "Recursos Pesqueiros e Engenharia de Pesca",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6387)
                        },
                        new
                        {
                            Id = "3028ad00-3df0-4338-9d2c-6bda3a9a0cf8",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6501),
                            Name = "Ciência e Tecnologia de Alimentos",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6501)
                        },
                        new
                        {
                            Id = "9d61781b-04ca-4bd0-b4fc-1a9f307d36d6",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6569),
                            Name = "Administração",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6569)
                        },
                        new
                        {
                            Id = "9992f633-0a3e-478b-af9e-b33f590678f1",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Ciências Contábeis",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6686)
                        },
                        new
                        {
                            Id = "0e49596d-bac8-4c87-831e-3e27c94fe9a0",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6752),
                            Name = "Ciências Econômicas",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6753)
                        },
                        new
                        {
                            Id = "20ec1045-1af2-4102-846f-254c804511c9",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6853),
                            Name = "Comunicação",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6853)
                        },
                        new
                        {
                            Id = "e69f1ade-b103-4de6-8eaa-3912b0648efb",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6921),
                            Name = "Direito",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(6921)
                        },
                        new
                        {
                            Id = "755c7f1a-4a85-4ff7-ac6c-f940cb5548ab",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7022),
                            Name = "Serviço Social",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7023)
                        },
                        new
                        {
                            Id = "41c450ab-a0d5-46b5-a850-390ea80492b7",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7090),
                            Name = "Turismo",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7090)
                        },
                        new
                        {
                            Id = "abcd3a04-231a-4270-a27b-4f378951951b",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7193),
                            Name = "Arquitetura e Urbanismo",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7193)
                        },
                        new
                        {
                            Id = "baa38234-bcb3-4a79-9d1a-9f1b241d4918",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7258),
                            Name = "Planejamento Urbano e Regional",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7258)
                        },
                        new
                        {
                            Id = "23b4fb46-f872-4188-bfe5-d977e759586b",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7363),
                            Name = "Demografia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7363)
                        },
                        new
                        {
                            Id = "a7c0d069-59a5-4017-aa6a-e5b8030b2b88",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7466),
                            Name = "Museologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7466)
                        },
                        new
                        {
                            Id = "d19bec43-2bcd-46d1-9173-adb39bd09540",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7532),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7533)
                        },
                        new
                        {
                            Id = "33a0e7b8-3aa8-49cd-8cf9-c0acefca39c1",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7619),
                            Name = "Sociologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7620)
                        },
                        new
                        {
                            Id = "ac46cfec-31d2-4ad9-b015-8c2b307d09ec",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7687),
                            Name = "Antropologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7688)
                        },
                        new
                        {
                            Id = "d6b91195-6e5f-4209-bb56-123fdb9ac3c5",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7799),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7799)
                        },
                        new
                        {
                            Id = "a0ac4e4c-807b-4bc8-a995-94dfb6fd6034",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7867),
                            Name = "Geografia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(7867)
                        },
                        new
                        {
                            Id = "97c020b9-896d-4814-8f09-732b853709c1",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8046),
                            Name = "Psicologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8046)
                        },
                        new
                        {
                            Id = "46c7ebef-ee4a-45dc-b69d-45f75d57f35c",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8118),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8119)
                        },
                        new
                        {
                            Id = "2e39b4f0-3096-45b8-ad44-92d11d48e0ae",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8223),
                            Name = "Teologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8223)
                        },
                        new
                        {
                            Id = "d89df958-e072-45d8-9368-e68bf6384cc0",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8289),
                            Name = "Ciência Política",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8289)
                        },
                        new
                        {
                            Id = "42b28b76-759c-4f70-b821-6f5b00acff28",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8389),
                            Name = "Relações Internacionais",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8390)
                        },
                        new
                        {
                            Id = "44bf120f-316b-4af3-a762-bfd02032050e",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8487),
                            Name = "Linguística",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8487)
                        },
                        new
                        {
                            Id = "d5f796a2-5987-441c-a9c2-f0ad5ad061d6",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8555),
                            Name = "Letras",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8555)
                        },
                        new
                        {
                            Id = "c37433f9-65ec-4112-a4cf-8bfe26f33f13",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8651),
                            Name = "Artes",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8651)
                        },
                        new
                        {
                            Id = "b3376652-fb1b-44cd-9353-1a1fef9fbb40",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8717),
                            Name = "Música",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8717)
                        },
                        new
                        {
                            Id = "009a2e71-8e9d-4c41-9719-142bb586a5fe",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8827),
                            Name = "Teatro",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8827)
                        },
                        new
                        {
                            Id = "581ce315-354e-476d-979b-57cff81a5170",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8891),
                            Name = "Artes Visuais",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(8892)
                        },
                        new
                        {
                            Id = "c634df09-5ae8-4737-8118-937e0a665c7c",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9011),
                            Name = "Ciência e Tecnologia Ambiental",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9011)
                        },
                        new
                        {
                            Id = "41f0c3a1-fd12-4e71-bc67-a1b3905fd1a7",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9079),
                            Name = "Ciência e Tecnologia dos Materiais",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9080)
                        },
                        new
                        {
                            Id = "b65e4ce6-720a-4569-8cc2-d68f96f11e8f",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9179),
                            Name = "Interdisciplinar",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9180)
                        },
                        new
                        {
                            Id = "56bc8090-0794-41ec-9ebb-882c2559ee63",
                            CreatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9244),
                            Name = "Biotecnologia",
                            UpdatedAt = new DateTime(2024, 8, 10, 12, 57, 37, 562, DateTimeKind.Utc).AddTicks(9245)
                        });
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Meta", "Stairways.Core.Models.RoadmapEntity.Meta#RoadmapMeta", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ImageURL")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("Privacy")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Roadmaps", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("DoneItemsHashs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Stairways.Core.Models.RoadmapEntity", b =>
                {
                    b.HasOne("Stairways.Core.Models.UserEntity", "Author")
                        .WithMany("Roadmaps")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stairways.Core.Models.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Stairways.Core.Models.UserEntity", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
